### PR TITLE
Add ROS Humble compatibility for parameter callbacks

### PR DESCRIPTION
**Pull request by wentasah**
Use conditional compilation based on rclcpp version to support both Humble (rclcpp 16.x) and later distributions (Iron 17.x+). The PostSetParametersCallback API was added in Iron, so for Humble the save-on-update functionality is handled in the OnSetParametersCallback instead, while later distributions use the proper post-set callback.

This fixes the build errors on Humble while maintaining optimal behavior on newer distributions.

Specifically, the error is the following and was introduced in #73:

    In file included from server/src/parameter_server.cpp:15:
    server/include/parameter_server.h:75:3: error: 'PostSetParametersCallbackHandle' does not name a
    type; did you mean 'OnSetParametersCallbackHandle'?
       75 |   PostSetParametersCallbackHandle::SharedPtr post_set_callback_handler_;
          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
although humble branch does not have this https://github.com/fujitatomoya/ros2_persist_parameter_server/blob/9b3f2a749e919807b9a76972b92a2a7b451dcf87/server/include/parameter_server.h#L66-L76, we probably keep this as API negotiation just to be safe.

**Comment by fujitatomoya** [comment]
@wentasah sorry for being really late to get back to this. rolling workflow is failing because of this PR, can you check on that? or we can close this because we already have humble branch in this repository. this should not happen with appropriate branch.

**Comment by wentasah** [comment]
I think I fixed the problem. The include which actually defines `RCLCPP_VERSION_MAJOR` was missing. Now `./scripts/build-verification.sh` passes when running locally. However, feel free to drop this change. If there is a separate humble branch, it doesn't make sense to complicate the code by humble compatibility.

**Review by fujitatomoya — APPROVED** [review]
lgtm
